### ISSUE TITLE
`json-canonicalization` バージョン`0.3.2` がyankされたため `bundle install` に失敗する

### ISSUE THREAD

**Issue by yuicho** [kmycode/mastodon#331]
### バグの再現手順

1. TAG`kb5.10-lts` もしくは TAG`kb9.1`に切り替える
2. リポジトリの最上位ディレクトリで `docker build .` を実施

### 期待する動作

イメージのビルドが完了する

### 実際の動作

エラーが発生してビルドが完了しない
```
 > [build 7/8] RUN bundle install -j"$(nproc)":                                         
0.848 Bundler 2.4.10 is running, but your lockfile was generated with 2.4.20. Installing Bundler 2.4.20 and restarting using that version.
4.019 Fetching gem metadata from https://rubygems.org/.
4.198 Fetching bundler 2.4.20
4.392 Installing bundler 2.4.20
6.082 Fetching gem metadata from https://rubygems.org/........
19.33 Fetching https://github.com/stanhu/omniauth-cas.git
21.17 Fetching https://github.com/jhawthorn/nsa.git
22.70 Fetching https://github.com/mastodon/rails-settings-cached.git
24.63 Fetching https://github.com/ClearlyClaire/webpush.git
26.62 Your bundle is locked to json-canonicalization (0.3.2) from rubygems repository
26.62 https://rubygems.org/ or installed locally, but that version can no longer be
26.62 found in that source. That means the author of json-canonicalization (0.3.2) has
26.62 removed it. You'll need to update your bundle to a version other than
26.62 json-canonicalization (0.3.2) that hasn't been removed in order to install.
```

### 詳しい情報

Gemfileにて `json-canonicalization` のバージョン `0.3.2` が指定されています。
https://github.com/kmycode/mastodon/blob/77a1cabb97fce68915b49ae90842d10132402687/Gemfile.lock#L378

しかしながら https://rubygems.org/gems/json-canonicalization/versions/0.3.2 を確認したところ、該当バージョンがyankされていました。
> このバージョンはヤンクされ、直接のダウンロードや依存関係になっている可能性がある他のgemは利用できません。
> バージョン履歴:
> [1.0.0](https://rubygems.org/gems/json-canonicalization/versions/1.0.0) - December 04, 2023 (10KB)
> [0.3.2](https://rubygems.org/gems/json-canonicalization/versions/0.3.2) - May 02, 2023 (10KB) ヤンク済み
> [0.3.1](https://rubygems.org/gems/json-canonicalization/versions/0.3.1) - November 27, 2022 (10KB)
> [0.3.0](https://rubygems.org/gems/json-canonicalization/versions/0.3.0) - December 13, 2021 (10KB)
> [0.2.1](https://rubygems.org/gems/json-canonicalization/versions/0.2.1) - February 13, 2021 (10KB)
> [0.2.0](https://rubygems.org/gems/json-canonicalization/versions/0.2.0) - December 23, 2019 (9.5KB)

### バグが発生したkmyblueサーバーのドメイン

mstdn.yuicho.net

### バグが発生したkmyblueのバージョン

kb5.10-lts, kb9.1

### OS

Debian 11.7

### その他の詳細情報

インストールスクリプトにも同様の `bundle install` が存在します。
試せてはいませんが、非Docker環境でも古いバージョンからのアップデートや新規インストールでは失敗すると思われます。

**Comment by kmycode** [comment]
ありがとうございます、そちら本家4.2.3で直ってます
kmyblueも本日中にリリース出しますのでお待ちください。
ご迷惑おかけしています
