### ISSUE TITLE
[WebUI] BT/Fav済み投稿を引用投稿すると表示上していないことになる

### ISSUE THREAD

**Issue by yuicho** [kmycode/mastodon#557]
### バグの再現手順

1. 何かしらの投稿で「ブースト」もしくは「お気に入り」を行う
2. 同じ投稿を引用して投稿する

### 期待する動作

「ブースト」や「お気に入り」の表示は変化しない

### 実際の動作

1で行った「ブースト」や「お気に入り」がされていない表示になる（更新すれば戻る）

### 詳しい情報

※画面が消えた瞬間はreloadをしています

https://github.com/kmycode/mastodon/assets/43964607/51e33d50-c02a-4ac6-a7b9-bac2a14c8fe6

### バグが発生したkmyblueサーバーのドメイン

mstdn.yuicho.net / si.okin-jp.net

### バグが発生したkmyblueのバージョン

10.4 / 11.0-dev

### ブラウザの名前

Safari バージョン17.2.1 (19617.1.17.11.12)

### OS

macOS 14.2.1（23C71）

### その他の詳細情報

Google Chrome 121.0.6167.160 でも再現できました

**Comment by kmycode** [comment]
原因は未調査ですが、#367 と似ていると感じました
仮に #367 の対処でこっちも解決した場合、こっちも一緒にクローズします
